In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import scipy.optimize
import numpy.linalg

In [2]:
asset_prices = pd.read_csv("Acutal Testing Data.csv", index_col=0)

In [3]:
asset_price_predictions_1 = pd.read_csv("Predicted Testing Data Analyst 1.csv", index_col=0)
asset_price_predictions_2 = pd.read_csv("Predicted Testing Data Analyst 2.csv", index_col=0)
asset_price_predictions_3 = pd.read_csv("Predicted Testing Data Analyst 3.csv", index_col=0)

In [4]:
def allocate_portfolio(asset_prices, asset_price_predictions_1,asset_price_predictions_2,asset_price_predictions_3):
    
    # This simple strategy equally weights all assets every period
    # (called a 1/n strategy).
    
    n_assets = len(asset_prices)
    n = 9
    weights = np.repeat(1 / n, n)
    return weights

In [5]:
linear_weights = allocate_portfolio(asset_prices, asset_price_predictions_1, asset_price_predictions_2, asset_price_predictions_3)

def percentage_change_computed_df(df):
    for x in range(0,9):   
        df['shift'+ str(x)] = df[df.columns[x]].shift(1)
        df['PercentChange'+ str(x)] = (df[df.columns[x]] - df['shift'+ str(x)]).div(df['shift'+ str(x)]) * 100
        df=df.drop(columns=('shift'+str(x)))
    return df

def weighted_percentage_df(df, weights):
    returns = df.loc[:,"PercentChange0":"PercentChange8"]
    return np.dot(returns, weights)

def sharpe(r):
    print(np.mean(r))
    print(np.std(r))
    return np.mean(r)/np.std(r)

In [6]:
asset_prices = percentage_change_computed_df(asset_prices)
asset_prices['Total_Returns'] = weighted_percentage_df(asset_prices, linear_weights)
asset_prices

,A,B,C,D,E,F,G,H,I,PercentChange0,PercentChange1,PercentChange2,PercentChange3,PercentChange4,PercentChange5,PercentChange6,PercentChange7,PercentChange8,Total_Returns
0,141.964897,226.352949,146.484337,77.539808,134.944262,32.982797,167.440304,297.091832,3091.003490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,144.935575,227.882208,145.000811,78.897964,139.777286,33.608131,172.101489,305.086648,3101.989323,2.092543,0.675608,-1.012754,1.751561,3.581497,1.895940,2.783789,2.691025,0.355413,1.646069
2,144.437134,234.666980,149.455145,81.378646,137.287929,33.521216,173.138616,304.388169,3134.173443,-0.343905,2.977316,3.071937,3.144164,-1.780945,-0.258612,0.602625,-0.228945,1.037532,0.913463
3,139.034096,231.480569,146.563009,83.680871,140.464937,32.373154,166.264334,300.779456,3122.525940,-3.740754,-1.357844,-1.935119,2.829029,2.314120,-3.424882,-3.970392,-1.185563,-0.371629,-1.204781
4,141.213983,233.275829,147.956318,79.816857,134.809211,31.813596,167.837537,312.957644,3134.811377,1.567879,0.775556,0.950655,-4.617560,-4.026433,-1.728464,0.946206,4.048876,0.393445,-0.187760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2504,1297.164867,2994.203816,686.117089,62.320904,78.924931,113.435158,4456.158943,21357.880970,127459.822000,-0.031889,-2.228050,-0.184947,4.465466,2.395281,3.188293,2.253707,3.923959,2.991834,1.863739
2505,1291.161511,2938.950066,674.352204,62.961496,77.684331,109.623823,4515.854224,22519.939970,127735.030200,-0.462806,-1.845357,-1.714705,1.027893,-1.571873,-3.359924,1.339613,5.440891,0.215918,-0.103372
2506,1289.726586,2910.861481,673.740238,62.632459,77.276593,107.954424,4682.722399,22005.634000,129251.684400,-0.111134,-0.955735,-0.090749,-0.522601,-0.524865,-1.522843,3.695163,-2.283780,1.187344,-0.125467
2507,1291.052193,2985.814154,686.296262,64.223488,79.928203,113.039260,4853.785794,22499.341580,122875.124800,0.102782,2.574931,1.863630,2.540263,3.431323,4.710169,3.653076,2.243551,-4.933444,1.798476
2508,1290.774077,2952.930299,701.380062,64.373123,79.099436,110.911987,4833.175064,21521.423970,124208.625800,-0.021542,-1.101336,2.197855,0.232992,-1.036889,-1.881889,-0.424632,-4.346428,1.085249,-0.588513

In [7]:
# Linear Weights Sharpe
returns = asset_prices.loc[:,"PercentChange0":"PercentChange8"].iloc[1:,:]
sharpe(asset_prices['Total_Returns'])

0.10954913009029703
1.4799752725944006

0.07402091921323598

In [8]:
def covmatrix(returns):
    return pd.DataFrame(np.cov(np.transpose(returns)))

In [9]:
cov_matrix = covmatrix(returns)
cov_matrix

,0,1,2,3,4,5,6,7,8
0,2.306292,1.298762,1.141528,0.963251,1.130399,1.005148,1.310736,1.154267,1.031804
1,1.298762,5.858559,1.689227,1.549967,1.660967,1.762331,2.160481,2.114981,1.782104
2,1.141528,1.689227,3.308783,1.345887,1.482503,1.440832,1.577871,1.400238,1.178210
3,0.963251,1.549967,1.345887,6.583104,4.265342,4.115271,1.461041,1.196537,1.108968
4,1.130399,1.660967,1.482503,4.265342,8.168224,4.506419,1.651950,1.400073,1.313188
5,1.005148,1.762331,1.440832,4.115271,4.506419,7.711765,1.707326,1.450864,1.288094
6,1.310736,2.160481,1.577871,1.461041,1.651950,1.707326,6.515720,2.675231,2.238241
7,1.154267,2.114981,1.400238,1.196537,1.400073,1.450864,2.675231,6.039092,2.082123
8,1.031804,1.782104,1.178210,1.108968,1.313188,1.288094,2.238241,2.082123,5.711375

In [10]:
def min_risk_func(x):
    a, b, c, d, e, f, g, h = list(zip(x))
    i = 1-a[0]-b[0]-c[0]-d[0]-e[0]-f[0]-g[0]-h[0]
    weights = np.array([a[0], b[0], c[0], d[0], e[0], f[0], g[0], h[0], i])
    return np.dot(weights, np.dot(cov_matrix, weights))

In [11]:
guess = np.repeat(1 / 9, 8)
min_risk_weights = scipy.optimize.minimize(min_risk_func, guess).x
min_risk_weights = np.append(min_risk_weights, (1-sum(min_risk_weights)))
min_risk_weights

array([0.46702264, 0.02967513, 0.20877639, 0.07952321, 0.00674079,
       0.03106646, 0.01257171, 0.0614187 , 0.10320496])

In [12]:
asset_prices = percentage_change_computed_df(asset_prices)
asset_prices['Total_Returns'] = weighted_percentage_df(asset_prices, min_risk_weights)
asset_prices

,A,B,C,D,E,F,G,H,I,PercentChange0,PercentChange1,PercentChange2,PercentChange3,PercentChange4,PercentChange5,PercentChange6,PercentChange7,PercentChange8,Total_Returns
0,141.964897,226.352949,146.484337,77.539808,134.944262,32.982797,167.440304,297.091832,3091.003490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,144.935575,227.882208,145.000811,78.897964,139.777286,33.608131,172.101489,305.086648,3101.989323,2.092543,0.675608,-1.012754,1.751561,3.581497,1.895940,2.783789,2.691025,0.355413,1.245164
2,144.437134,234.666980,149.455145,81.378646,137.287929,33.521216,173.138616,304.388169,3134.173443,-0.343905,2.977316,3.071937,3.144164,-1.780945,-0.258612,0.602625,-0.228945,1.037532,0.899676
3,139.034096,231.480569,146.563009,83.680871,140.464937,32.373154,166.264334,300.779456,3122.525940,-3.740754,-1.357844,-1.935119,2.829029,2.314120,-3.424882,-3.970392,-1.185563,-0.371629,-2.218229
4,141.213983,233.275829,147.956318,79.816857,134.809211,31.813596,167.837537,312.957644,3134.811377,1.567879,0.775556,0.950655,-4.617560,-4.026433,-1.728464,0.946206,4.048876,0.393445,0.806860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2504,1297.164867,2994.203816,686.117089,62.320904,78.924931,113.435158,4456.158943,21357.880970,127459.822000,-0.031889,-2.228050,-0.184947,4.465466,2.395281,3.188293,2.253707,3.923959,2.991834,0.928790
2505,1291.161511,2938.950066,674.352204,62.961496,77.684331,109.623823,4515.854224,22519.939970,127735.030200,-0.462806,-1.845357,-1.714705,1.027893,-1.571873,-3.359924,1.339613,5.440891,0.215918,-0.288830
2506,1289.726586,2910.861481,673.740238,62.632459,77.276593,107.954424,4682.722399,22005.634000,129251.684400,-0.111134,-0.955735,-0.090749,-0.522601,-0.524865,-1.522843,3.695163,-2.283780,1.187344,-0.162889
2507,1291.052193,2985.814154,686.296262,64.223488,79.928203,113.039260,4853.785794,22499.341580,122875.124800,0.102782,2.574931,1.863630,2.540263,3.431323,4.710169,3.653076,2.243551,-4.933444,0.559528
2508,1290.774077,2952.930299,701.380062,64.373123,79.099436,110.911987,4833.175064,21521.423970,124208.625800,-0.021542,-1.101336,2.197855,0.232992,-1.036889,-1.881889,-0.424632,-4.346428,1.085249,0.208905

In [13]:
# Min Risk Weights Sharpe
sharpe(asset_prices['Total_Returns'])

0.1043615907941115
1.2894178846938613

0.08093698096865583

In [14]:
asset_prices.loc[:,"A":"I"].iloc[-1]

A      1290.774077
B      2952.930299
C       701.380062
D        64.373123
E        79.099436
F       110.911987
G      4833.175064
H     21521.423970
I    124208.625800
Name: 2508, dtype: float64

In [15]:
shares = pd.read_csv("Shares Outstanding.csv")
shares.drop(columns=['Unnamed: 0'], inplace=True)
market_caps = shares.iloc[0] * asset_prices.loc[:,"A":"I"].iloc[-1]
total_market_cap = sum(market_caps)
wmkt = market_caps / total_market_cap
lamb = 1
implied_returns = lamb*(np.dot(cov_matrix,wmkt))

In [16]:
asset_prices['Total_Returns'] = weighted_percentage_df(asset_prices, wmkt)
returns = asset_prices.loc[:,"PercentChange0":"PercentChange8"].iloc[1:,:]
sharpe(asset_prices['Total_Returns'])

0.18615164023518277
1.9496897167062428

0.09547757196445736

In [17]:
asset_price_predictions_1 = pd.read_csv("Predicted Testing Data Analyst 1.csv", index_col=0)
asset_price_predictions_1 = asset_price_predictions_1[::21]
asset_price_predictions_2 = pd.read_csv("Predicted Testing Data Analyst 2.csv", index_col=0)
asset_price_predictions_2 = asset_price_predictions_2[::21]
asset_price_predictions_3 = pd.read_csv("Predicted Testing Data Analyst 3.csv", index_col=0)
asset_price_predictions_3 = asset_price_predictions_3[::21]

asset_price_predictions_1 = percentage_change_computed_df(asset_price_predictions_1)
asset_price_predictions_1

,A,B,C,D,E,F,G,H,I,PercentChange0,PercentChange1,PercentChange2,PercentChange3,PercentChange4,PercentChange5,PercentChange6,PercentChange7,PercentChange8
0,151.334280,248.634224,91.986690,129.593431,75.578648,31.268725,217.696233,244.289579,3205.820805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,140.506463,170.233406,162.203129,101.014005,218.061794,22.546984,372.746989,136.233053,4129.776508,-7.154900,-31.532593,76.333258,-22.053144,188.523015,-27.892859,71.223445,-44.232966,28.821190
42,131.638458,222.721949,146.443072,83.506710,61.998978,52.797580,279.670459,201.633165,1898.754007,-6.311457,30.833280,-9.716247,-17.331552,-71.568161,134.166931,-24.970431,48.006053,-54.022839
63,160.762391,168.955881,228.405013,66.419323,141.546983,32.294821,189.400944,157.379568,6117.127219,22.124183,-24.140444,55.968465,-20.462293,128.305349,-38.832763,-32.277100,-21.947578,222.165336
84,208.819746,402.346959,167.324906,158.873556,149.184612,21.103624,198.972676,247.477082,3885.468770,29.893406,138.137291,-26.742017,139.197796,5.395826,-34.653225,5.053687,57.248546,-36.482132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2415,1030.236373,2972.546007,930.716947,68.616511,149.760352,92.559722,3421.565379,11840.186030,183107.362900,21.448624,27.024732,36.738287,-23.459738,172.828611,29.048259,11.477314,33.351515,21.915319
2436,996.033425,4487.881834,426.605211,56.755054,85.345967,132.564574,3284.295801,12158.744890,171949.777100,-3.319913,50.977708,-54.163808,-17.286592,-43.011641,43.220583,-4.011894,2.690489,-6.093466
2457,1158.648060,4634.572391,1237.560682,41.439717,113.615510,112.724593,4858.759837,17895.765700,139386.905000,16.326223,3.268592,190.095069,-26.984975,33.123467,-14.966277,47.939167,47.184318,-18.937432
2478,818.013117,4306.580920,399.115315,45.990545,52.230508,73.913169,4061.386602,18885.929710,128771.134100,-29.399345,-7.077060,-67.749839,10.981801,-54.028717,-34.430308,-16.411044,5.532951,-7.616046
2499,1479.443365,3239.526505,493.989667,164.301783,67.526838,130.799797,6862.670409,17809.928630,107962.241600,80.858147,-24.777299,23.771163,257.251223,29.286199,76.964131,68.973582,-5.697369,-16.159594

In [18]:
p1_cov = covmatrix(asset_price_predictions_1.loc[:,"PercentChange0":"PercentChange8"].iloc[1:,:])/21
bl_cov = numpy.linalg.inv((numpy.linalg.inv(cov_matrix)+ numpy.linalg.inv(p1_cov)))
#pd.DataFrame(bl_cov)
Q = ((asset_price_predictions_1.iloc[-1].loc["A":"I"]/100 + 1)**(1/21)-1)*100
bl_returns = bl_cov@(numpy.linalg.inv(cov_matrix)@implied_returns + numpy.linalg.inv(p1_cov)@Q)
bl_returns

array([1.98391195, 3.75345552, 2.27535305, 2.24270654, 2.39578363,
       2.70505993, 5.40882371, 6.15082265, 4.95545384])

In [19]:
bl_weights = numpy.linalg.inv(cov_matrix)@bl_returns/lamb
bl_weights = bl_weights/sum(bl_weights)
bl_weights

array([ 0.03599331,  0.07257258, -0.00686035,  0.01521205, -0.01837153,
        0.02927172,  0.2135906 ,  0.39395706,  0.26463455])

In [20]:
# if we use the last row the sharpe ratio came out to be 0.09547757...
#weighted_percentage_df(asset_prices, wmkt)
wmkt

A    0.001792
B    0.002382
C    0.001320
D    0.000889
E    0.000499
F    0.001221
G    0.257612
H    0.527868
I    0.206418
dtype: float64

In [21]:
df = asset_price_predictions_1
df2 = asset_prices
df2

,A,B,C,D,E,F,G,H,I,PercentChange0,PercentChange1,PercentChange2,PercentChange3,PercentChange4,PercentChange5,PercentChange6,PercentChange7,PercentChange8,Total_Returns
0,141.964897,226.352949,146.484337,77.539808,134.944262,32.982797,167.440304,297.091832,3091.003490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,144.935575,227.882208,145.000811,78.897964,139.777286,33.608131,172.101489,305.086648,3101.989323,2.092543,0.675608,-1.012754,1.751561,3.581497,1.895940,2.783789,2.691025,0.355413,2.220687
2,144.437134,234.666980,149.455145,81.378646,137.287929,33.521216,173.138616,304.388169,3134.173443,-0.343905,2.977316,3.071937,3.144164,-1.780945,-0.258612,0.602625,-0.228945,1.037532,0.260679
3,139.034096,231.480569,146.563009,83.680871,140.464937,32.373154,166.264334,300.779456,3122.525940,-3.740754,-1.357844,-1.935119,2.829029,2.314120,-3.424882,-3.970392,-1.185563,-0.371629,-1.738355
4,141.213983,233.275829,147.956318,79.816857,134.809211,31.813596,167.837537,312.957644,3134.811377,1.567879,0.775556,0.950655,-4.617560,-4.026433,-1.728464,0.946206,4.048876,0.393445,2.459926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2504,1297.164867,2994.203816,686.117089,62.320904,78.924931,113.435158,4456.158943,21357.880970,127459.822000,-0.031889,-2.228050,-0.184947,4.465466,2.395281,3.188293,2.253707,3.923959,2.991834,3.272931
2505,1291.161511,2938.950066,674.352204,62.961496,77.684331,109.623823,4515.854224,22519.939970,127735.030200,-0.462806,-1.845357,-1.714705,1.027893,-1.571873,-3.359924,1.339613,5.440891,0.215918,3.250281
2506,1289.726586,2910.861481,673.740238,62.632459,77.276593,107.954424,4682.722399,22005.634000,129251.684400,-0.111134,-0.955735,-0.090749,-0.522601,-0.524865,-1.522843,3.695163,-2.283780,1.187344,-0.013706
2507,1291.052193,2985.814154,686.296262,64.223488,79.928203,113.039260,4853.785794,22499.341580,122875.124800,0.102782,2.574931,1.863630,2.540263,3.431323,4.710169,3.653076,2.243551,-4.933444,1.125522
2508,1290.774077,2952.930299,701.380062,64.373123,79.099436,110.911987,4833.175064,21521.423970,124208.625800,-0.021542,-1.101336,2.197855,0.232992,-1.036889,-1.881889,-0.424632,-4.346428,1.085249,-2.182082

In [29]:
for x in range(0,2509):   
    market_caps = shares.iloc[0] * asset_prices.loc[:,"A":"I"].iloc[x//21]
    total_market_cap = sum(market_caps)
    wmkt = market_caps / total_market_cap
    lamb = 1
    implied_returns = lamb*(np.dot(cov_matrix,wmkt))
    
    p1_cov = covmatrix(asset_price_predictions_1.loc[:,"PercentChange0":"PercentChange8"].iloc[1:,:])/21
    bl_cov = numpy.linalg.inv((numpy.linalg.inv(cov_matrix)+ numpy.linalg.inv(p1_cov)))
    Q = ((asset_price_predictions_1.iloc[x//21].loc["A":"I"]/100 + 1)**(1/21)-1)*100
    bl_returns = bl_cov@(numpy.linalg.inv(cov_matrix)@implied_returns + numpy.linalg.inv(p1_cov)@Q)
    bl_weights = numpy.linalg.inv(cov_matrix)@bl_returns/lamb
    bl_weights = bl_weights/sum(bl_weights)
    
    asset_prices['Total_Returns_final'][x] = weighted_percentage_df(asset_prices, bl_weights)[x]
    print(pd.DataFrame(weighted_percentage_df(asset_prices, bl_weights)))

             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.930960
2     0.665758
3    -1.620661
4     1.140643
...        ...
2504  2.823942
2505  1.779852
2506  0.763467
2507  0.821786
2508 -1.046647

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.946786
2     0.653001
3    -1.575504
4     1.031821
...        ...
2504  2.826131
2505  1.709236
2506  0.802737
2507  0.877864
2508 -1.005087

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]

             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.947862
2     0.662271
3    -1.712099
4     1.187416
...        ...
2504  2.791518
2505  1.782701
2506  0.800524
2507  0.948149
2508 -1.060097

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.861058
2     0.701267
3    -1.545213
4     1.076173
...        ...
2504  2.815630
2505  1.694021
2506  0.742305
2507  0.696524
2508 -0.958834

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.901841
2     0.690126
3    -1.553596
4     1.107200
...        ...
2504  2.761176
2505  1.720717
2506  0.688006
2507  0.816137
2508 -1.036382

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]

             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.969205
2     0.623118
3    -1.604741
4     1.178805
...        ...
2504  2.867110
2505  1.864005
2506  0.690408
2507  0.905261
2508 -1.122829

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.932901
2     0.643951
3    -1.583706
4     1.240263
...        ...
2504  2.886806
2505  1.907350
2506  0.667069
2507  0.808850
2508 -1.138656

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]

             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.890457
2     0.676760
3    -1.613455
4     1.167756
...        ...
2504  2.829343
2505  1.780288
2506  0.743821
2507  0.756751
2508 -1.011219

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.879485
2     0.695629
3    -1.654104
4     1.223595
...        ...
2504  2.769646
2505  1.775510
2506  0.731643
2507  0.767736
2508 -1.029209

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.906318
2     0.687002
3    -1.668802
4     1.152834
...        ...
2504  2.714245
2505  1.687621
2506  0.769037
2507  0.859359
2508 -1.018602

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]

             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.928074
2     0.660932
3    -1.588610
4     1.181750
...        ...
2504  2.876302
2505  1.852096
2506  0.722117
2507  0.790750
2508 -1.089770

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.919583
2     0.664542
3    -1.591399
4     1.163605
...        ...
2504  2.813019
2505  1.786342
2506  0.733077
2507  0.811560
2508 -1.067756

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]

             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.922869
2     0.643932
3    -1.612973
4     1.118205
...        ...
2504  2.756730
2505  1.677712
2506  0.706397
2507  0.859082
2508 -1.065242

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.893337
2     0.673896
3    -1.545104
4     1.042274
...        ...
2504  2.776308
2505  1.644971
2506  0.691181
2507  0.816328
2508 -1.004650

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.909558
2     0.652997
3    -1.499525
4     1.051493
...        ...
2504  2.775341
2505  1.655462
2506  0.626159
2507  0.822752
2508 -1.080920

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]

             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.869173
2     0.698361
3    -1.547518
4     1.099104
...        ...
2504  2.715154
2505  1.641159
2506  0.605185
2507  0.815832
2508 -1.044123

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.878558
2     0.707626
3    -1.508484
4     1.023379
...        ...
2504  2.869318
2505  1.707952
2506  0.659956
2507  0.757997
2508 -1.006576

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]

             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.901280
2     0.649447
3    -1.553534
4     1.132178
...        ...
2504  2.839938
2505  1.748280
2506  0.647541
2507  0.772695
2508 -1.076552

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.912375
2     0.705114
3    -1.618525
4     1.060841
...        ...
2504  2.691880
2505  1.620731
2506  0.734866
2507  0.957773
2508 -1.019427

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.883635
2     0.709521
3    -1.625694
4     1.037880
...        ...
2504  2.737080
2505  1.608067
2506  0.752221
2507  0.772271
2508 -0.948205

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]

             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.811967
2     0.765382
3    -1.571232
4     1.033150
...        ...
2504  2.728591
2505  1.556448
2506  0.706226
2507  0.712817
2508 -0.936521

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.831739
2     0.751057
3    -1.545645
4     0.941066
...        ...
2504  2.698754
2505  1.492044
2506  0.710975
2507  0.766124
2508 -0.887791

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.874466
2     0.713892
3    -1.552318
4     1.011140
...        ...
2504  2.711602
2505  1.571985
2506  0.650185
2507  0.793666
2508 -0.997842

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]

             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.835449
2     0.749401
3    -1.516057
4     0.985214
...        ...
2504  2.662560
2505  1.510954
2506  0.642186
2507  0.825371
2508 -0.961067

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.871252
2     0.724062
3    -1.592773
4     1.020373
...        ...
2504  2.733038
2505  1.575476
2506  0.657650
2507  0.908566
2508 -1.004199

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]

             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.904230
2     0.687548
3    -1.680703
4     1.047653
...        ...
2504  2.706369
2505  1.572351
2506  0.746653
2507  0.931644
2508 -0.981627

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.855166
2     0.739307
3    -1.541448
4     1.012001
...        ...
2504  2.753016
2505  1.599711
2506  0.665590
2507  0.775766
2508 -0.981281

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.837204
2     0.737145
3    -1.583236
4     1.045907
...        ...
2504  2.615916
2505  1.510989
2506  0.657154
2507  0.816699
2508 -0.958242

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]

             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.804404
2     0.761406
3    -1.660332
4     1.156957
...        ...
2504  2.639485
2505  1.585760
2506  0.698043
2507  0.707869
2508 -0.938849

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.835171
2     0.747066
3    -1.616538
4     1.077805
...        ...
2504  2.684547
2505  1.582115
2506  0.722146
2507  0.763217
2508 -0.938475

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]

             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.815634
2     0.785198
3    -1.632490
4     1.012332
...        ...
2504  2.645251
2505  1.486857
2506  0.745723
2507  0.854115
2508 -0.898399

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.829170
2     0.747868
3    -1.644209
4     1.054755
...        ...
2504  2.652958
2505  1.517171
2506  0.746505
2507  0.704772
2508 -0.915382

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.843351
2     0.761023
3    -1.676003
4     1.022683
...        ...
2504  2.685772
2505  1.527831
2506  0.805577
2507  0.839994
2508 -0.889319

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]

             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.806295
2     0.773963
3    -1.612807
4     0.984974
...        ...
2504  2.663461
2505  1.464836
2506  0.796560
2507  0.687015
2508 -0.853241

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.741164
2     0.876576
3    -1.651016
4     1.027927
...        ...
2504  2.546722
2505  1.416215
2506  0.798726
2507  0.778269
2508 -0.812928

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]
             0
0          NaN
1     1.774124
2     0.820667
3    -1.615205
4     0.918833
...        ...
2504  2.568404
2505  1.334188
2506  0.809541
2507  0.780852
2508 -0.799203

[2509 rows x 1 columns]

             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.785186
2     0.829133
3    -1.699517
4     1.001459
...        ...
2504  2.580395
2505  1.403411
2506  0.866852
2507  0.774913
2508 -0.819472

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.811233
2     0.770853
3    -1.691717
4     0.986921
...        ...
2504  2.666740
2505  1.443014
2506  0.877361
2507  0.721355
2508 -0.816359

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.797173
2     0.843220
3    -1.747150
4     0.993044
...        ...
2504  2.501203
2505  1.350433
2506  0.925003
2507  0.808856
2508 -0.802942

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.844761
2     0.768732
3    -1.698700
4     0.975007
...        ...
2504  2.624053
2505  1.437214
2506  0.870682
2507  0.808767
2508 -0.851479

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.819726
2     0.797816
3    -1.692241
4     0.962904
...        ...
2504  2.637695
2505  1.424620
2506  0.911396
2507  0.743980
2508 -0.820482

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]

             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.855350
2     0.773107
3    -1.847812
4     1.021119
...        ...
2504  2.584776
2505  1.415183
2506  1.015644
2507  0.838535
2508 -0.805759

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.842730
2     0.767421
3    -1.739038
4     0.997966
...        ...
2504  2.654812
2505  1.448588
2506  0.951955
2507  0.737249
2508 -0.842756

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]

             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.776319
2     0.809747
3    -1.672407
4     0.976635
...        ...
2504  2.625911
2505  1.407146
2506  0.905467
2507  0.614192
2508 -0.767078

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.816988
2     0.785852
3    -1.702375
4     1.014424
...        ...
2504  2.630634
2505  1.458352
2506  0.916679
2507  0.720987
2508 -0.824854

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]

             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.736218
2     0.849195
3    -1.723240
4     1.021533
...        ...
2504  2.643705
2505  1.425996
2506  0.955155
2507  0.534787
2508 -0.721067

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.816360
2     0.796864
3    -1.771296
4     1.015142
...        ...
2504  2.551504
2505  1.379385
2506  0.956525
2507  0.734837
2508 -0.813360

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.869172
2     0.748301
3    -1.793747
4     1.061845
...        ...
2504  2.647585
2505  1.520438
2506  0.957804
2507  0.799376
2508 -0.851197

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]

             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.812039
2     0.798235
3    -1.746389
4     1.050583
...        ...
2504  2.682254
2505  1.521471
2506  0.944225
2507  0.714326
2508 -0.806682

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.785930
2     0.794371
3    -1.675326
4     0.995559
...        ...
2504  2.593511
2505  1.407067
2506  0.880944
2507  0.639566
2508 -0.782744

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.863562
2     0.734413
3    -1.798302
4     1.089753
...        ...
2504  2.698189
2505  1.563879
2506  0.962803
2507  0.787681
2508 -0.848268

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]

             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.876805
2     0.715887
3    -1.821945
4     1.131972
...        ...
2504  2.680380
2505  1.582837
2506  0.970798
2507  0.788421
2508 -0.872989

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.882705
2     0.757524
3    -1.793221
4     1.085291
...        ...
2504  2.682477
2505  1.580000
2506  0.998346
2507  0.856442
2508 -0.880830

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]

             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.832203
2     0.766955
3    -1.845062
4     1.115578
...        ...
2504  2.618927
2505  1.499523
2506  0.976085
2507  0.734930
2508 -0.826759

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.829237
2     0.786326
3    -1.842414
4     1.127170
...        ...
2504  2.584595
2505  1.498915
2506  0.969448
2507  0.788489
2508 -0.838039

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.868534
2     0.761088
3    -1.818042
4     1.070431
...        ...
2504  2.639613
2505  1.519088
2506  1.018391
2507  0.819708
2508 -0.839700

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]

             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.821814
2     0.793156
3    -1.822327
4     1.075611
...        ...
2504  2.619816
2505  1.481970
2506  0.985291
2507  0.766738
2508 -0.800436

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.905598
2     0.696910
3    -1.856166
4     1.113735
...        ...
2504  2.710650
2505  1.585571
2506  0.999166
2507  0.814818
2508 -0.886550

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]

             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.871481
2     0.749343
3    -1.884641
4     1.064287
...        ...
2504  2.584747
2505  1.441137
2506  1.001440
2507  0.852428
2508 -0.836999

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.913319
2     0.749494
3    -1.872443
4     1.044146
...        ...
2504  2.639643
2505  1.517861
2506  1.052710
2507  0.974178
2508 -0.854071

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.812890
2     0.841579
3    -1.766487
4     0.954886
...        ...
2504  2.560894
2505  1.386563
2506  0.946742
2507  0.911291
2508 -0.757608

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]

             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.898227
2     0.771853
3    -1.898457
4     1.038982
...        ...
2504  2.617375
2505  1.481974
2506  1.020744
2507  0.984663
2508 -0.852490

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.939609
2     0.680983
3    -1.823302
4     1.087592
...        ...
2504  2.654116
2505  1.557701
2506  0.890227
2507  0.973257
2508 -0.962275

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]

             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.914075
2     0.716646
3    -1.847542
4     1.092893
...        ...
2504  2.607701
2505  1.526653
2506  0.907208
2507  0.975363
2508 -0.922739

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.912820
2     0.748578
3    -1.833057
4     1.061401
...        ...
2504  2.591724
2505  1.506982
2506  0.922450
2507  1.058418
2508 -0.925863

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]
             0
0          NaN
1     1.880714
2     0.744778
3    -1.827004
4     1.059420
...        ...
2504  2.587617
2505  1.471383
2506  0.894688
2507  0.925281
2508 -0.884949

[2509 rows x 1 columns]

             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.900737
2     0.724248
3    -1.831396
4     1.040586
...        ...
2504  2.620443
2505  1.476782
2506  0.911621
2507  0.951852
2508 -0.896189

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.882674
2     0.748427
3    -1.746246
4     1.067593
...        ...
2504  2.642975
2505  1.533338
2506  0.806661
2507  0.990059
2508 -0.966013

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.909179
2     0.749515
3    -1.863967
4     1.105114
...        ...
2504  2.532220
2505  1.490833
2506  0.819591
2507  1.105448
2508 -0.971287

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.859892
2     0.777038
3    -1.841706
4     1.023739
...        ...
2504  2.538706
2505  1.394423
2506  0.903294
2507  0.981416
2508 -0.856613

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]

             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.904070
2     0.742714
3    -1.821595
4     1.043991
...        ...
2504  2.648937
2505  1.506585
2506  0.912437
2507  0.971289
2508 -0.928797

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.853072
2     0.784125
3    -1.772605
4     0.988344
...        ...
2504  2.638374
2505  1.441776
2506  0.905720
2507  0.957571
2508 -0.862444

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.903858
2     0.747640
3    -1.801622
4     1.052773
...        ...
2504  2.594625
2505  1.503581
2506  0.878602
2507  0.955111
2508 -0.926611

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]

             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.863293
2     0.766299
3    -1.872421
4     1.105179
...        ...
2504  2.524190
2505  1.446334
2506  0.850854
2507  1.013918
2508 -0.903759

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.900527
2     0.741061
3    -1.770845
4     0.979203
...        ...
2504  2.593413
2505  1.420378
2506  0.813031
2507  0.998960
2508 -0.941356

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]

             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.867512
2     0.746201
3    -1.787745
4     1.065113
...        ...
2504  2.618077
2505  1.486111
2506  0.825179
2507  0.991644
2508 -0.922691

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.895426
2     0.742694
3    -1.756495
4     1.045615
...        ...
2504  2.657283
2505  1.522287
2506  0.853733
2507  0.938176
2508 -0.961188

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.893623
2     0.719915
3    -1.835233
4     1.064883
...        ...
2504  2.571429
2505  1.452315
2506  0.847026
2507  0.969400
2508 -0.920856

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]

             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.846665
2     0.766106
3    -1.882730
4     1.094015
...        ...
2504  2.457353
2505  1.363895
2506  0.808890
2507  0.971801
2508 -0.896935

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.869719
2     0.754222
3    -1.792728
4     1.038257
...        ...
2504  2.595948
2505  1.443721
2506  0.868704
2507  0.909363
2508 -0.912809

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]
             0
0          NaN
1     1.850184
2     0.750745
3    -1.859311
4     1.085271
...        ...
2504  2.561944
2505  1.422148
2506  0.873184
2507  0.865554
2508 -0.883325

[2509 rows x 1 columns]

             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.848565
2     0.770333
3    -1.679540
4     0.923982
...        ...
2504  2.649160
2505  1.404345
2506  0.890374
2507  0.759658
2508 -0.852510

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.828059
2     0.753875
3    -1.709211
4     1.015990
...        ...
2504  2.588603
2505  1.398250
2506  0.785666
2507  0.706137
2508 -0.900540

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]

             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.836127
2     0.744948
3    -1.716426
4     0.965411
...        ...
2504  2.620031
2505  1.372987
2506  0.822735
2507  0.724245
2508 -0.869637

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.858723
2     0.748631
3    -1.792896
4     0.999825
...        ...
2504  2.659397
2505  1.429676
2506  0.917085
2507  0.767904
2508 -0.868387

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.868557
2     0.710134
3    -1.762888
4     0.986798
...        ...
2504  2.577374
2505  1.354070
2506  0.846961
2507  0.761494
2508 -0.898726

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]

             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.871448
2     0.749696
3    -1.802803
4     1.027168
...        ...
2504  2.580978
2505  1.425621
2506  0.855930
2507  0.906985
2508 -0.898574

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.766700
2     0.855696
3    -1.841689
4     1.014750
...        ...
2504  2.496355
2505  1.293944
2506  0.942226
2507  0.774936
2508 -0.772981

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]

             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.853333
2     0.735432
3    -1.844508
4     1.061198
...        ...
2504  2.577899
2505  1.398671
2506  0.868038
2507  0.780648
2508 -0.890063

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.854130
2     0.758047
3    -1.868239
4     1.011746
...        ...
2504  2.556002
2505  1.340473
2506  0.957845
2507  0.841438
2508 -0.851714

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.871023
2     0.747611
3    -1.917794
4     1.107479
...        ...
2504  2.526875
2505  1.402518
2506  0.879502
2507  0.919417
2508 -0.928494

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]

             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.827104
2     0.765980
3    -1.855088
4     1.077952
...        ...
2504  2.525992
2505  1.372582
2506  0.884381
2507  0.762001
2508 -0.861136

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.860969
2     0.749974
3    -1.922726
4     1.117078
...        ...
2504  2.504783
2505  1.399084
2506  0.929661
2507  0.878750
2508 -0.883427

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]

             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.827808
2     0.771595
3    -1.862382
4     1.029643
...        ...
2504  2.554281
2505  1.340457
2506  0.932108
2507  0.798009
2508 -0.837875

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.834225
2     0.771848
3    -1.812600
4     1.048342
...        ...
2504  2.571356
2505  1.412674
2506  0.870351
2507  0.782176
2508 -0.856303

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.788338
2     0.770024
3    -1.814723
4     1.053946
...        ...
2504  2.571282
2505  1.350173
2506  0.862013
2507  0.691948
2508 -0.827681

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]

             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.892894
2     0.705382
3    -1.832709
4     1.007993
...        ...
2504  2.578370
2505  1.375550
2506  0.879638
2507  0.932187
2508 -0.908165

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.828518
2     0.776406
3    -1.863558
4     1.064560
...        ...
2504  2.517702
2505  1.364102
2506  0.950913
2507  0.787598
2508 -0.832161

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]

             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.844392
2     0.742883
3    -1.819980
4     1.058355
...        ...
2504  2.555033
2505  1.383938
2506  0.881605
2507  0.781699
2508 -0.884489

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.812136
2     0.770782
3    -1.867684
4     1.088246
...        ...
2504  2.536913
2505  1.372155
2506  0.896539
2507  0.773225
2508 -0.842216

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.848194
2     0.736411
3    -1.829201
4     1.059732
...        ...
2504  2.570045
2505  1.400098
2506  0.887183
2507  0.770738
2508 -0.869882

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.875991
2     0.736289
3    -1.840810
4     1.040819
...        ...
2504  2.563131
2505  1.401687
2506  0.931049
2507  0.847887
2508 -0.883725

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.860452
2     0.754515
3    -1.810350
4     1.044166
...        ...
2504  2.559297
2505  1.410212
2506  0.880913
2507  0.869837
2508 -0.893217

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]

             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.800278
2     0.807747
3    -1.857770
4     1.071153
...        ...
2504  2.467080
2505  1.329945
2506  0.906001
2507  0.732566
2508 -0.823753

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.842965
2     0.756870
3    -1.798804
4     1.026862
...        ...
2504  2.550519
2505  1.373216
2506  0.871224
2507  0.774355
2508 -0.871175

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.799373
2     0.801890
3    -1.855241
4     1.039806
...        ...
2504  2.470944
2505  1.297117
2506  0.918003
2507  0.757053
2508 -0.807202

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.837720
2     0.752405
3    -1.790918
4     1.072644
...        ...
2504  2.586430
2505  1.436448
2506  0.873444
2507  0.723967
2508 -0.880617

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.825925
2     0.757156
3    -1.849246
4     1.063491
...        ...
2504  2.522576
2505  1.353512
2506  0.901706
2507  0.732447
2508 -0.843000

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]

             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.813476
2     0.762709
3    -1.847874
4     1.062808
...        ...
2504  2.536967
2505  1.341701
2506  0.923110
2507  0.667636
2508 -0.839643

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.826042
2     0.725241
3    -1.805348
4     1.112384
...        ...
2504  2.619917
2505  1.452909
2506  0.858801
2507  0.602465
2508 -0.884410

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.821880
2     0.744348
3    -1.879410
4     1.165193
...        ...
2504  2.503492
2505  1.406185
2506  0.846193
2507  0.672758
2508 -0.897972

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.787538
2     0.803083
3    -1.875656
4     1.079407
...        ...
2504  2.511236
2505  1.340133
2506  0.962487
2507  0.660927
2508 -0.792425

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.791666
2     0.792625
3    -1.830105
4     1.113558
...        ...
2504  2.498233
2505  1.376374
2506  0.890405
2507  0.676468
2508 -0.845293

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]

             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.799700
2     0.782998
3    -1.816187
4     1.051387
...        ...
2504  2.500371
2505  1.328047
2506  0.890967
2507  0.700348
2508 -0.825396

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.747990
2     0.832967
3    -1.799954
4     1.063082
...        ...
2504  2.524018
2505  1.339550
2506  0.914292
2507  0.583205
2508 -0.775717

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]
             0
0          NaN
1     1.758122
2     0.813043
3    -1.771355
4     1.052404
...        ...
2504  2.500631
2505  1.318500
2506  0.854564
2507  0.629841
2508 -0.808840

[2509 rows x 1 columns]

             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.769612
2     0.799875
3    -1.825650
4     1.086286
...        ...
2504  2.466839
2505  1.298978
2506  0.873664
2507  0.607610
2508 -0.834469

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.764738
2     0.809780
3    -1.870647
4     1.160670
...        ...
2504  2.431794
2505  1.336252
2506  0.845768
2507  0.714410
2508 -0.856634

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]

             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.803176
2     0.779157
3    -1.877882
4     1.182467
...        ...
2504  2.492192
2505  1.409354
2506  0.891363
2507  0.664922
2508 -0.895538

[2509 rows x 1 columns]
             0
0          NaN
1     1.837790
2     0.764384
3    -1.898232
4     1.130722
...        ...
2504  2.517333
2505  1.405879
2506  0.900307
2507  0.761556
2508 -0.890434

[2509 rows x 1 columns]
             0
0          NaN
1     1.837790
2     0.764384
3    -1.898232
4     1.130722
...        ...
2504  2.517333
2505  1.405879
2506  0.900307
2507  0.761556
2508 -0.890434

[2509 rows x 1 columns]
             0
0          NaN
1     1.837790
2     0.764384
3    -1.898232
4     1.130722
...        ...
2504  2.517333
2505  1.405879
2506  0.900307
2507  0.761556
2508 -0.890434

[2509 rows x 1 columns]
             0
0          NaN
1     1.837790
2     0.764384
3    -1.898232
4     1.130722
...        ...
2504  2.517333
2505  1.405879
2506  0.900307
2507  0.761556
2508 -0.890434

[2509 rows x 1 columns]
             0
0          NaN
1     1.837790
2     0.764384
3    -1.898232
4     1.130722
...        ...
2504  2.517333
2505  1.405879
2506  0.900307
2507  0.761556
2508 -0.890434

[2509 rows x 1 columns]
             0
0          NaN
1     1.837790
2     0.764384
3    -1.898232
4     1.130722
...        ...
2504  2.517333
2505  1.405879
2506  0.900307
2507  0.761556
2508 -0.890434

[2509 rows x 1 columns]
             0
0          NaN
1     1.837790
2     0.764384
3    -1.898232
4     1.130722
...        ...
2504  2.517333
2505  1.405879
2506  0.900307
2507  0.761556
2508 -0.890434

[2509 rows x 1 columns]
             0
0          NaN
1     1.837790
2     0.764384
3    -1.898232
4     1.130722
...        ...
2504  2.517333
2505  1.405879
2506  0.900307
2507  0.761556
2508 -0.890434

[2509 rows x 1 columns]
             0
0          NaN
1     1.837790
2     0.764384
3    -1.898232
4     1.130722
...        ...
2504  2.517333
2505  1.405879
2506  0.900307
2507  0.761556
2508 -0.890434

[2509 rows x 1 columns]
             0
0          NaN
1     1.837790
2     0.764384
3    -1.898232
4     1.130722
...        ...
2504  2.517333
2505  1.405879
2506  0.900307
2507  0.761556
2508 -0.890434

[2509 rows x 1 columns]

In [30]:
asset_prices

,A,B,C,D,E,F,G,H,I,PercentChange0,PercentChange1,PercentChange2,PercentChange3,PercentChange4,PercentChange5,PercentChange6,PercentChange7,PercentChange8,Total_Returns,Total_Returns_final
0,141.964897,226.352949,146.484337,77.539808,134.944262,32.982797,167.440304,297.091832,3091.003490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,144.935575,227.882208,145.000811,78.897964,139.777286,33.608131,172.101489,305.086648,3101.989323,2.092543,0.675608,-1.012754,1.751561,3.581497,1.895940,2.783789,2.691025,0.355413,2.220687,1.930960
2,144.437134,234.666980,149.455145,81.378646,137.287929,33.521216,173.138616,304.388169,3134.173443,-0.343905,2.977316,3.071937,3.144164,-1.780945,-0.258612,0.602625,-0.228945,1.037532,0.260679,0.665758
3,139.034096,231.480569,146.563009,83.680871,140.464937,32.373154,166.264334,300.779456,3122.525940,-3.740754,-1.357844,-1.935119,2.829029,2.314120,-3.424882,-3.970392,-1.185563,-0.371629,-1.738355,-1.620661
4,141.213983,233.275829,147.956318,79.816857,134.809211,31.813596,167.837537,312.957644,3134.811377,1.567879,0.775556,0.950655,-4.617560,-4.026433,-1.728464,0.946206,4.048876,0.393445,2.459926,1.140643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2504,1297.164867,2994.203816,686.117089,62.320904,78.924931,113.435158,4456.158943,21357.880970,127459.822000,-0.031889,-2.228050,-0.184947,4.465466,2.395281,3.188293,2.253707,3.923959,2.991834,3.272931,2.517333
2505,1291.161511,2938.950066,674.352204,62.961496,77.684331,109.623823,4515.854224,22519.939970,127735.030200,-0.462806,-1.845357,-1.714705,1.027893,-1.571873,-3.359924,1.339613,5.440891,0.215918,3.250281,1.405879
2506,1289.726586,2910.861481,673.740238,62.632459,77.276593,107.954424,4682.722399,22005.634000,129251.684400,-0.111134,-0.955735,-0.090749,-0.522601,-0.524865,-1.522843,3.695163,-2.283780,1.187344,-0.013706,0.900307
2507,1291.052193,2985.814154,686.296262,64.223488,79.928203,113.039260,4853.785794,22499.341580,122875.124800,0.102782,2.574931,1.863630,2.540263,3.431323,4.710169,3.653076,2.243551,-4.933444,1.125522,0.761556
2508,1290.774077,2952.930299,701.380062,64.373123,79.099436,110.911987,4833.175064,21521.423970,124208.625800,-0.021542,-1.101336,2.197855,0.232992,-1.036889,-1.881889,-0.424632,-4.346428,1.085249,-2.182082,-0.890434

In [31]:
sharpe(asset_prices['Total_Returns_final'])

0.1614023127399241
1.7196083530446842

0.09385992598497807